stateDiagram-v2
初稿 --> 定稿 : 定稿
定稿 --> 正式审核中 : 送审
正式审核中 --> 审核通过 : 审核通过
正式审核中 --> 审核未通过 : 审核未通过
正式审核中 --> 审核通过（有修改） : 审核通过（有修改）
审核通过 --> 已通知客户 : 已通知客户
审核未通过 --> 客户修改中（驳回） : 通知客户未通过
客户修改中（驳回） --> 定稿 : 定稿
审核通过（有修改） --> 客户修改中（有修改） : 通知客户修改
客户修改中（有修改） --> 已通知客户 : 已通知客户
审核通过（有修改） --> 内部修改完成 : 已内部修改
内部修改完成 --> 已通知客户 : 已通知客户
