stateDiagram-v2
WaitingForPPS --> OrganizedForSending : Organize
OrganizedForSending --> InternalReviewed : InternalReviewApprove
InternalReviewed --> InReview : SendForReview
InReview --> ReviewApproved : ReviewApprove
InReview --> ReviewRejected : ReviewReject
InReview --> ReviewApprovedWithChanges : ReviewApproveWithChanges
ReviewApproved --> CustomerNotified : NotifyCustomer
ReviewRejected --> CustomerModifyingForRejection : NotifyCustomerOfRejection
CustomerModifyingForRejection --> OrganizedForSending : Organize
ReviewApprovedWithChanges --> OrganizedForSending : Organize
